### ISSUE TITLE
The digit dataset ?

### ISSUE THREAD

**Issue by cjjjy** [desh2608/dnn-hmm-asr#1]
where can I download the digit training dataset ?

**Comment by desh2608** [comment]
I have provided a small sample in the README. Although I cannot provide the full dataset, I believe it would be quite similar to [this corpus](https://github.com/Jakobovski/free-spoken-digit-dataset). Note, however, that you would have to perform MFCC (or any feature) extraction on your own. There are several tools available for this purpose, such as [librosa](https://librosa.org/doc/latest/index.html).
